game_id: "461"
week_number: 1
output_dir: "~/Desktop/fantasy/2025/output"
team_names_path: "team_names.csv"
credentials_path: "credentials/"
league_ids:
  - "920510" # Barn Szn Pass
  - "515852"  # 6 U Court
  - "349625" # Crank City
  - "635676" # Stump Field 
  - "521684" # Orange and Blue
  - "863282" # Eight
  - "891930" # Champions
  - "836169" # Lil PP Gang
complete_column_names:
  - "Team Name"
  - "Name"
  - "League"
  - "Wins"
  - "Losses"
  - "Points For"
  - "Points Against"
  - "Point Differential"
  - "League Rank"
  - "Streak"
  - "Draft Position"
  - "Draft Grade"
  - "Roster Moves"
  - "Number of Trades"
email_column_names:
  - "Team Name"
  - "Name"
  - "League"
  - "Wins"
  - "Losses"
  - "Points For"
  - "Points Against"